// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_token.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createApiToken = `-- name: CreateApiToken :one
INSERT INTO api_tokens (
    user_id, name, token_hash, expires_at
) VALUES (
    $1, $2, $3, $4
) RETURNING id, user_id, name, token_hash, expires_at, created_at
`

type CreateApiTokenParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	Name      string             `json:"name"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateApiToken(ctx context.Context, arg CreateApiTokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, createApiToken,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteApiToken = `-- name: DeleteApiToken :exec
DELETE FROM api_tokens 
WHERE id = $1 AND user_id = $2
`

type DeleteApiTokenParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteApiToken(ctx context.Context, arg DeleteApiTokenParams) error {
	_, err := q.db.Exec(ctx, deleteApiToken, arg.ID, arg.UserID)
	return err
}

const getUserByTokenHash = `-- name: GetUserByTokenHash :one
SELECT u.id, u.email, u.password_hash, u.name, u.role, u.preferences, u.created_at, u.updated_at FROM api_tokens t
JOIN users u ON t.user_id = u.id
WHERE t.token_hash = $1 
  AND (t.expires_at IS NULL OR t.expires_at > NOW())
`

func (q *Queries) GetUserByTokenHash(ctx context.Context, tokenHash string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByTokenHash, tokenHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.Preferences,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApiTokens = `-- name: ListApiTokens :many
SELECT id, name, created_at, expires_at 
FROM api_tokens 
WHERE user_id = $1 
ORDER BY created_at DESC
`

type ListApiTokensRow struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) ListApiTokens(ctx context.Context, userID uuid.UUID) ([]ListApiTokensRow, error) {
	rows, err := q.db.Query(ctx, listApiTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApiTokensRow
	for rows.Next() {
		var i ListApiTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
