// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type RootCategoryType string

const (
	RootCategoryTypeGROWTH RootCategoryType = "GROWTH"
	RootCategoryTypeLIFE   RootCategoryType = "LIFE"
	RootCategoryTypeWORK   RootCategoryType = "WORK"
	RootCategoryTypeHOBBY  RootCategoryType = "HOBBY"
	RootCategoryTypeOTHER  RootCategoryType = "OTHER"
)

func (e *RootCategoryType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RootCategoryType(s)
	case string:
		*e = RootCategoryType(s)
	default:
		return fmt.Errorf("unsupported scan type for RootCategoryType: %T", src)
	}
	return nil
}

type NullRootCategoryType struct {
	RootCategoryType RootCategoryType `json:"root_category_type"`
	Valid            bool             `json:"valid"` // Valid is true if RootCategoryType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRootCategoryType) Scan(value interface{}) error {
	if value == nil {
		ns.RootCategoryType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RootCategoryType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRootCategoryType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RootCategoryType), nil
}

type TaskStatus string

const (
	TaskStatusTODO  TaskStatus = "TODO"
	TaskStatusDOING TaskStatus = "DOING"
	TaskStatusDONE  TaskStatus = "DONE"
)

func (e *TaskStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskStatus(s)
	case string:
		*e = TaskStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskStatus: %T", src)
	}
	return nil
}

type NullTaskStatus struct {
	TaskStatus TaskStatus `json:"task_status"`
	Valid      bool       `json:"valid"` // Valid is true if TaskStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskStatus), nil
}

type UserRole string

const (
	UserRoleADMIN UserRole = "ADMIN"
	UserRoleUSER  UserRole = "USER"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type ApiToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Name      string             `json:"name"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Calendar struct {
	ID                  uuid.UUID          `json:"id"`
	UserID              uuid.UUID          `json:"user_id"`
	Name                string             `json:"name"`
	Color               pgtype.Text        `json:"color"`
	Description         pgtype.Text        `json:"description"`
	SyncToken           string             `json:"sync_token"`
	SupportedComponents []string           `json:"supported_components"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type Category struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Name      string             `json:"name"`
	RootType  RootCategoryType   `json:"root_type"`
	Color     pgtype.Text        `json:"color"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ChecklistItem struct {
	ID          uuid.UUID `json:"id"`
	TaskID      uuid.UUID `json:"task_id"`
	Content     string    `json:"content"`
	IsCompleted bool      `json:"is_completed"`
	Position    int32     `json:"position"`
}

type Project struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	CategoryID  uuid.UUID          `json:"category_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Color       pgtype.Text        `json:"color"`
	IsArchived  bool               `json:"is_archived"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Result struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	ProjectID    uuid.UUID          `json:"project_id"`
	TargetTaskID pgtype.UUID        `json:"target_task_id"`
	Type         string             `json:"type"`
	Value        pgtype.Numeric     `json:"value"`
	RecordedAt   pgtype.Timestamptz `json:"recorded_at"`
	Note         pgtype.Text        `json:"note"`
}

type ScheduledEvent struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	ProjectID       uuid.UUID          `json:"project_id"`
	CalendarID      pgtype.UUID        `json:"calendar_id"`
	Title           string             `json:"title"`
	Description     pgtype.Text        `json:"description"`
	Location        pgtype.Text        `json:"location"`
	StartAt         pgtype.Timestamptz `json:"start_at"`
	EndAt           pgtype.Timestamptz `json:"end_at"`
	IsAllDay        bool               `json:"is_all_day"`
	ExternalEventID pgtype.Text        `json:"external_event_id"`
	IcalUid         pgtype.Text        `json:"ical_uid"`
	Etag            pgtype.Text        `json:"etag"`
	Sequence        int32              `json:"sequence"`
	Status          pgtype.Text        `json:"status"`
	Transparency    pgtype.Text        `json:"transparency"`
	Rrule           pgtype.Text        `json:"rrule"`
	Dtstamp         pgtype.Timestamptz `json:"dtstamp"`
	Url             pgtype.Text        `json:"url"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Task struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	ProjectID    uuid.UUID          `json:"project_id"`
	Title        string             `json:"title"`
	NoteMarkdown pgtype.Text        `json:"note_markdown"`
	Status       TaskStatus         `json:"status"`
	DueDate      pgtype.Timestamptz `json:"due_date"`
	Priority     pgtype.Int2        `json:"priority"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	CalendarID   pgtype.UUID        `json:"calendar_id"`
	IcalUid      pgtype.Text        `json:"ical_uid"`
	Etag         pgtype.Text        `json:"etag"`
	Sequence     int32              `json:"sequence"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
}

type TimeEntry struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	ProjectID       uuid.UUID          `json:"project_id"`
	TaskID          pgtype.UUID        `json:"task_id"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	EndedAt         pgtype.Timestamptz `json:"ended_at"`
	Note            pgtype.Text        `json:"note"`
	IsAutoGenerated bool               `json:"is_auto_generated"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type TimetableSlot struct {
	ID        uuid.UUID   `json:"id"`
	UserID    uuid.UUID   `json:"user_id"`
	ProjectID uuid.UUID   `json:"project_id"`
	DayOfWeek int16       `json:"day_of_week"`
	StartTime pgtype.Time `json:"start_time"`
	EndTime   pgtype.Time `json:"end_time"`
	Note      pgtype.Text `json:"note"`
	Location  pgtype.Text `json:"location"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Name         string             `json:"name"`
	Role         UserRole           `json:"role"`
	Preferences  []byte             `json:"preferences"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
