// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (
    user_id, name, root_type, color
) VALUES (
    $1, $2, $3, $4
) RETURNING id, user_id, name, root_type, color, created_at
`

type CreateCategoryParams struct {
	UserID   uuid.UUID        `json:"user_id"`
	Name     string           `json:"name"`
	RootType RootCategoryType `json:"root_type"`
	Color    pgtype.Text      `json:"color"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.UserID,
		arg.Name,
		arg.RootType,
		arg.Color,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.RootType,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    user_id, category_id, title, description, is_archived
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, user_id, category_id, title, description, is_archived, created_at, updated_at
`

type CreateProjectParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	CategoryID  uuid.UUID   `json:"category_id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	IsArchived  bool        `json:"is_archived"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.UserID,
		arg.CategoryID,
		arg.Title,
		arg.Description,
		arg.IsArchived,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, user_id, category_id, title, description, is_archived, created_at, updated_at FROM projects
WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetProjectParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, arg.ID, arg.UserID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, user_id, name, root_type, color, created_at FROM categories
WHERE user_id = $1
ORDER BY root_type, name
`

func (q *Queries) ListCategories(ctx context.Context, userID uuid.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.RootType,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT p.id, p.user_id, p.category_id, p.title, p.description, p.is_archived, p.created_at, p.updated_at, c.name as category_name, c.root_type, c.color
FROM projects p
JOIN categories c ON p.category_id = c.id
WHERE
    p.user_id = $1
    AND ($2::boolean IS NULL OR p.is_archived = $2)
ORDER BY p.updated_at DESC
`

type ListProjectsParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	IsArchived pgtype.Bool `json:"is_archived"`
}

type ListProjectsRow struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	CategoryID   uuid.UUID          `json:"category_id"`
	Title        string             `json:"title"`
	Description  pgtype.Text        `json:"description"`
	IsArchived   bool               `json:"is_archived"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	CategoryName string             `json:"category_name"`
	RootType     RootCategoryType   `json:"root_type"`
	Color        pgtype.Text        `json:"color"`
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]ListProjectsRow, error) {
	rows, err := q.db.Query(ctx, listProjects, arg.UserID, arg.IsArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsRow
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.IsArchived,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.RootType,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
