// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCalendar(ctx context.Context, arg CreateCalendarParams) (Calendar, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (ScheduledEvent, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetEventByICalUID(ctx context.Context, arg GetEventByICalUIDParams) (ScheduledEvent, error)
	GetProject(ctx context.Context, arg GetProjectParams) (Project, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListCalendars(ctx context.Context, userID pgtype.UUID) ([]Calendar, error)
	ListCategories(ctx context.Context, userID pgtype.UUID) ([]Category, error)
	ListEventsByRange(ctx context.Context, arg ListEventsByRangeParams) ([]ListEventsByRangeRow, error)
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]ListProjectsRow, error)
	UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) (User, error)
}

var _ Querier = (*Queries)(nil)
