// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createChecklistItem = `-- name: CreateChecklistItem :one
INSERT INTO checklist_items (
    task_id, content, position
) VALUES (
    $1, $2,
    (SELECT COALESCE(MAX(position), 0) + 1 FROM checklist_items WHERE task_id = $1)
) RETURNING id, task_id, content, is_completed, position
`

type CreateChecklistItemParams struct {
	TaskID  uuid.UUID `json:"task_id"`
	Content string    `json:"content"`
}

func (q *Queries) CreateChecklistItem(ctx context.Context, arg CreateChecklistItemParams) (ChecklistItem, error) {
	row := q.db.QueryRow(ctx, createChecklistItem, arg.TaskID, arg.Content)
	var i ChecklistItem
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Content,
		&i.IsCompleted,
		&i.Position,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    user_id, project_id, title, note_markdown, due_date, priority,
    calendar_id, ical_uid, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, user_id, project_id, title, note_markdown, status, due_date, priority, created_at, updated_at, calendar_id, ical_uid, etag, sequence, completed_at
`

type CreateTaskParams struct {
	UserID       uuid.UUID          `json:"user_id"`
	ProjectID    uuid.UUID          `json:"project_id"`
	Title        string             `json:"title"`
	NoteMarkdown pgtype.Text        `json:"note_markdown"`
	DueDate      pgtype.Timestamptz `json:"due_date"`
	Priority     pgtype.Int2        `json:"priority"`
	CalendarID   pgtype.UUID        `json:"calendar_id"`
	IcalUid      pgtype.Text        `json:"ical_uid"`
	Status       TaskStatus         `json:"status"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.UserID,
		arg.ProjectID,
		arg.Title,
		arg.NoteMarkdown,
		arg.DueDate,
		arg.Priority,
		arg.CalendarID,
		arg.IcalUid,
		arg.Status,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Title,
		&i.NoteMarkdown,
		&i.Status,
		&i.DueDate,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CalendarID,
		&i.IcalUid,
		&i.Etag,
		&i.Sequence,
		&i.CompletedAt,
	)
	return i, err
}

const deleteChecklistItem = `-- name: DeleteChecklistItem :exec
DELETE FROM checklist_items
WHERE id = $1
`

func (q *Queries) DeleteChecklistItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteChecklistItem, id)
	return err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE id = $1 AND user_id = $2
`

type DeleteTaskParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) error {
	_, err := q.db.Exec(ctx, deleteTask, arg.ID, arg.UserID)
	return err
}

const deleteTaskByICalUID = `-- name: DeleteTaskByICalUID :exec
DELETE FROM tasks
WHERE user_id = $1 AND ical_uid = $2
`

type DeleteTaskByICalUIDParams struct {
	UserID  uuid.UUID   `json:"user_id"`
	IcalUid pgtype.Text `json:"ical_uid"`
}

func (q *Queries) DeleteTaskByICalUID(ctx context.Context, arg DeleteTaskByICalUIDParams) error {
	_, err := q.db.Exec(ctx, deleteTaskByICalUID, arg.UserID, arg.IcalUid)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, user_id, project_id, title, note_markdown, status, due_date, priority, created_at, updated_at, calendar_id, ical_uid, etag, sequence, completed_at FROM tasks
WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetTaskParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetTask(ctx context.Context, arg GetTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, arg.ID, arg.UserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Title,
		&i.NoteMarkdown,
		&i.Status,
		&i.DueDate,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CalendarID,
		&i.IcalUid,
		&i.Etag,
		&i.Sequence,
		&i.CompletedAt,
	)
	return i, err
}

const getTaskByICalUID = `-- name: GetTaskByICalUID :one
SELECT id, user_id, project_id, title, note_markdown, status, due_date, priority, created_at, updated_at, calendar_id, ical_uid, etag, sequence, completed_at FROM tasks
WHERE user_id = $1 AND ical_uid = $2 LIMIT 1
`

type GetTaskByICalUIDParams struct {
	UserID  uuid.UUID   `json:"user_id"`
	IcalUid pgtype.Text `json:"ical_uid"`
}

func (q *Queries) GetTaskByICalUID(ctx context.Context, arg GetTaskByICalUIDParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByICalUID, arg.UserID, arg.IcalUid)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Title,
		&i.NoteMarkdown,
		&i.Status,
		&i.DueDate,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CalendarID,
		&i.IcalUid,
		&i.Etag,
		&i.Sequence,
		&i.CompletedAt,
	)
	return i, err
}

const listChecklistItems = `-- name: ListChecklistItems :many
SELECT id, task_id, content, is_completed, position FROM checklist_items
WHERE task_id = $1
ORDER BY position ASC
`

func (q *Queries) ListChecklistItems(ctx context.Context, taskID uuid.UUID) ([]ChecklistItem, error) {
	rows, err := q.db.Query(ctx, listChecklistItems, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChecklistItem
	for rows.Next() {
		var i ChecklistItem
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Content,
			&i.IsCompleted,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByCalendar = `-- name: ListTasksByCalendar :many
SELECT id, user_id, project_id, title, note_markdown, status, due_date, priority, created_at, updated_at, calendar_id, ical_uid, etag, sequence, completed_at FROM tasks
WHERE user_id = $1 AND calendar_id = $2
ORDER BY created_at DESC
`

type ListTasksByCalendarParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	CalendarID pgtype.UUID `json:"calendar_id"`
}

func (q *Queries) ListTasksByCalendar(ctx context.Context, arg ListTasksByCalendarParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByCalendar, arg.UserID, arg.CalendarID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Title,
			&i.NoteMarkdown,
			&i.Status,
			&i.DueDate,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CalendarID,
			&i.IcalUid,
			&i.Etag,
			&i.Sequence,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByCalendarAndRange = `-- name: ListTasksByCalendarAndRange :many
SELECT id, user_id, project_id, title, note_markdown, status, due_date, priority, created_at, updated_at, calendar_id, ical_uid, etag, sequence, completed_at FROM tasks
WHERE user_id = $1
  AND calendar_id = $2
  AND (due_date IS NULL OR (due_date >= $3 AND due_date <= $4))
ORDER BY created_at DESC
`

type ListTasksByCalendarAndRangeParams struct {
	UserID     uuid.UUID          `json:"user_id"`
	CalendarID pgtype.UUID        `json:"calendar_id"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) ListTasksByCalendarAndRange(ctx context.Context, arg ListTasksByCalendarAndRangeParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByCalendarAndRange,
		arg.UserID,
		arg.CalendarID,
		arg.StartTime,
		arg.EndTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Title,
			&i.NoteMarkdown,
			&i.Status,
			&i.DueDate,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CalendarID,
			&i.IcalUid,
			&i.Etag,
			&i.Sequence,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksWithStats = `-- name: ListTasksWithStats :many
SELECT
    t.id, t.project_id, t.title, t.status, t.due_date, t.priority,
    p.title as project_title, COALESCE(p.color, '#808080')::varchar as project_color,
    COUNT(ci.id) as total_items,
    COUNT(ci.id) FILTER (WHERE ci.is_completed) as done_items
FROM tasks t
JOIN projects p ON t.project_id = p.id
LEFT JOIN checklist_items ci ON t.id = ci.task_id
WHERE
    t.user_id = $1
    AND ($2::uuid IS NULL OR t.project_id = $2)
    AND ($3::task_status IS NULL OR t.status = $3)
    AND ($4::timestamptz IS NULL OR t.due_date >= $4)
    AND ($5::timestamptz IS NULL OR t.due_date <= $5)
GROUP BY t.id, p.id
ORDER BY
    CASE WHEN t.status = 'DONE' THEN 1 ELSE 0 END,
    t.due_date ASC NULLS LAST,
    t.created_at DESC
`

type ListTasksWithStatsParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	Status    NullTaskStatus     `json:"status"`
	FromDate  pgtype.Timestamptz `json:"from_date"`
	ToDate    pgtype.Timestamptz `json:"to_date"`
}

type ListTasksWithStatsRow struct {
	ID           uuid.UUID          `json:"id"`
	ProjectID    uuid.UUID          `json:"project_id"`
	Title        string             `json:"title"`
	Status       TaskStatus         `json:"status"`
	DueDate      pgtype.Timestamptz `json:"due_date"`
	Priority     pgtype.Int2        `json:"priority"`
	ProjectTitle string             `json:"project_title"`
	ProjectColor string             `json:"project_color"`
	TotalItems   int64              `json:"total_items"`
	DoneItems    int64              `json:"done_items"`
}

// タスクと同時に、チェックリストの進捗を取得
func (q *Queries) ListTasksWithStats(ctx context.Context, arg ListTasksWithStatsParams) ([]ListTasksWithStatsRow, error) {
	rows, err := q.db.Query(ctx, listTasksWithStats,
		arg.UserID,
		arg.ProjectID,
		arg.Status,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTasksWithStatsRow
	for rows.Next() {
		var i ListTasksWithStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Status,
			&i.DueDate,
			&i.Priority,
			&i.ProjectTitle,
			&i.ProjectColor,
			&i.TotalItems,
			&i.DoneItems,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChecklistItem = `-- name: UpdateChecklistItem :one
UPDATE checklist_items
SET 
    content = COALESCE($2, content),
    is_completed = COALESCE($3, is_completed),
    position = COALESCE($4, position)
WHERE id = $1
RETURNING id, task_id, content, is_completed, position
`

type UpdateChecklistItemParams struct {
	ID          uuid.UUID   `json:"id"`
	Content     pgtype.Text `json:"content"`
	IsCompleted pgtype.Bool `json:"is_completed"`
	Position    pgtype.Int4 `json:"position"`
}

func (q *Queries) UpdateChecklistItem(ctx context.Context, arg UpdateChecklistItemParams) (ChecklistItem, error) {
	row := q.db.QueryRow(ctx, updateChecklistItem,
		arg.ID,
		arg.Content,
		arg.IsCompleted,
		arg.Position,
	)
	var i ChecklistItem
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Content,
		&i.IsCompleted,
		&i.Position,
	)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET
    title = COALESCE($3, title),
    note_markdown = COALESCE($4, note_markdown),
    status = COALESCE($5, status),
    completed_at = COALESCE($6, completed_at),
    due_date = COALESCE($7, due_date),
    priority = COALESCE($8, priority),
    updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, project_id, title, note_markdown, status, due_date, priority, created_at, updated_at, calendar_id, ical_uid, etag, sequence, completed_at
`

type UpdateTaskParams struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	Title        pgtype.Text        `json:"title"`
	NoteMarkdown pgtype.Text        `json:"note_markdown"`
	Status       NullTaskStatus     `json:"status"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	DueDate      pgtype.Timestamptz `json:"due_date"`
	Priority     pgtype.Int2        `json:"priority"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.NoteMarkdown,
		arg.Status,
		arg.CompletedAt,
		arg.DueDate,
		arg.Priority,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Title,
		&i.NoteMarkdown,
		&i.Status,
		&i.DueDate,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CalendarID,
		&i.IcalUid,
		&i.Etag,
		&i.Sequence,
		&i.CompletedAt,
	)
	return i, err
}

const updateTaskByICalUID = `-- name: UpdateTaskByICalUID :one
UPDATE tasks
SET
    title = COALESCE($3, title),
    note_markdown = COALESCE($4, note_markdown),
    status = COALESCE($5, status),
    due_date = COALESCE($6, due_date),
    priority = COALESCE($7, priority),
    etag = COALESCE($8, etag),
    sequence = COALESCE($9, sequence),
    completed_at = COALESCE($10, completed_at),
    updated_at = NOW()
WHERE user_id = $1 AND ical_uid = $2
RETURNING id, user_id, project_id, title, note_markdown, status, due_date, priority, created_at, updated_at, calendar_id, ical_uid, etag, sequence, completed_at
`

type UpdateTaskByICalUIDParams struct {
	UserID       uuid.UUID          `json:"user_id"`
	IcalUid      pgtype.Text        `json:"ical_uid"`
	Title        pgtype.Text        `json:"title"`
	NoteMarkdown pgtype.Text        `json:"note_markdown"`
	Status       NullTaskStatus     `json:"status"`
	DueDate      pgtype.Timestamptz `json:"due_date"`
	Priority     pgtype.Int2        `json:"priority"`
	Etag         pgtype.Text        `json:"etag"`
	Sequence     pgtype.Int4        `json:"sequence"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateTaskByICalUID(ctx context.Context, arg UpdateTaskByICalUIDParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskByICalUID,
		arg.UserID,
		arg.IcalUid,
		arg.Title,
		arg.NoteMarkdown,
		arg.Status,
		arg.DueDate,
		arg.Priority,
		arg.Etag,
		arg.Sequence,
		arg.CompletedAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Title,
		&i.NoteMarkdown,
		&i.Status,
		&i.DueDate,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CalendarID,
		&i.IcalUid,
		&i.Etag,
		&i.Sequence,
		&i.CompletedAt,
	)
	return i, err
}
